project:
  name: Base API
  env: local

server:
  host: 0.0.0.0
  port: 8080
  write_timeout: 10 # Seconds
  read_timeout: 10 # Seconds
  idle_timeout: 60 # Seconds

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: go_base_app
  max_open_conns: 25
  max_idle_conns: 25
  max_idle_time: 900 # Seconds
  sslmode: disable