version: "3"

services:
  api:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: api
    restart: always
    depends_on:
      - postgres
    links:
      - postgres
    ports:
      - ${API_SERVER_PORT}:${API_SERVER_PORT}
    volumes:
      - ../.env:/opt/project/.env
  postgres:
    image: freematiq/postgres:latest
    container_name: postgres
    restart: always
    volumes:
      - ../../db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    command: postgres -c 'datestyle=iso,dmy'
  migrate:
    image: migrate/migrate:v4.16.2
    profiles: [ "build" ]
    volumes:
      - ../migrations:/migrations
    entrypoint: migrate -path ./migrations -database ${DB_DSN}
    command: [ "up" ]
    depends_on:
      - postgres
    links:
      - postgres
    restart: on-failure
  nginx:
    image: freematiq/nginx:latest
    container_name: nginx
    restart: always
    volumes:
      - ../../logs:/opt/logs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.template:ro
      - ./nginx/disallow-robots.txt:/etc/nginx/conf.d/disallow-robots.txt:ro
    environment:
      SERVER_NAME: ${SERVER_NAME}
      API_PORT: ${API_SERVER_PORT}
    depends_on:
      - api
    links:
      - api
    ports:
      - "80:80"
      - "443:443"